### PR TITLE
Add some tests & setup CI

### PR DESCRIPTION
**Pull request by k4nar**

### CODE REVIEW

**Comment by k4nar** [comment]
There is a failure with PG 9.6 because `SELECT 'foo'` returns the type `unknown` instead of `text`. I don't know how to fix this, and why it differ with PG 10+.

Also, the jobs fail randomly at the first test from time to time. I think this is because in some cases the DB is not ready.

**Review by entwanne — APPROVED** [review]

**Comment by entwanne** [comment]
The explanation for the error with PG 9.6 is here: https://www.postgresql.org/docs/current/typeconv-select.html

I don't know what to do, maybe we can explicitly cast the value to text? Or treat `unknown` type as text?

**Comment by k4nar** [comment]
Yep, that were I ended up last time as well. I don't think we can assume that `unknown` should be unicode. It sure is bytes though.

**Comment by k4nar** [comment]
We should probably test what asyncpg is doing about it.

**Comment by entwanne** [comment]
In asyncpg [the unknown type is decoded as text](https://github.com/MagicStack/asyncpg/blob/f0adefc73ac7169e92c9d22b999db4ebea08281b/asyncpg/protocol/codecs/pgproto.pyx#L215). I'll fix the code & merge.

**Pull request merged**
